version: "3.12"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  authsystem:
    build: ./auth_system
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  analysisserver:
    build: ./analysis_server
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate --fake &&
               python manage.py runserver 0.0.0.0:1234"
    ports:
      - "1234:1234"
    depends_on:
      - db
      - authsystem

  contentserver:
    build: ./content_server
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
    env_file:
      - ./content_server/.env
    depends_on:
      - db
      - authsystem

  bankserver:
    build: ./bank_server
    ports:
      - 8888:8888
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
    depends_on:
      - db

  gateway:
    build: ./gateway
    ports:
      - 8080:8080
    depends_on:
      - authsystem
      - analysisserver
      - contentserver
      - bankserver

  xlearnfrontend:
    build: ./xlearn
    ports:
      - "3000:3000"
    depends_on:
      - gateway
