// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "@/styles/globals.css";
// import Provider from "@/redux/provider";
import { Footer } from "@/components/common";
import { Navbar } from "./(dashboard)/_components/navbar";
// import { Setup } from "@/components/utils";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "collegeX",
//   description: "Learn Free, Learn Fast, Learn Everything!",
// };

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { ToastProvider } from '@/components/providers/toaster-provider'
// import { ConfettiProvider } from '@/components/providers/confetti-provider'
import Provider from "@/redux/provider";
import { Setup } from "@/components/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Provider>
//           <Setup />
//           {/* <ConfettiProvider /> */}
//           {/* <ToastProvider /> */}

//           {children}
//         </Provider>
//       </body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Setup />
          {children}
        </Provider>
      </body>
    </html>
  );
}
